
import java.awt.*;
import javax.swing.*;
import javax.swing.filechooser.FileSystemView;
import javax.swing.undo.AbstractUndoableEdit;
import javax.swing.undo.UndoManager;
import javax.swing.undo.UndoableEdit;




public class gui extends javax.swing.JFrame {

    
    private Color lastPlayer;  
    final int xsize=6;
    final int ysize=6;
    static int redWin=0;
    static int blueWin=0;
    private final JLabel [][] board=new JLabel[6][6];
    
    
    ConnectFour logic=new ConnectFour();
    
    private final String[] lastEvent=new String[1];
    
   
    
    public gui() {
        
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("chenqinj-ConnectFour");
        jLabelCurrentStatus.setText("Waiting for RED Player...");

        jLabelRedWin.setText("RED Winning:"+redWin);
        jLabelBlueWin.setText("BLUE Winning:"+blueWin);
       
        jMenuItemUndo.setEnabled(false);
    
        board[0][0]=jLabel00; board[0][1]=jLabel01; board[0][2]=jLabel02; board[0][3]=jLabel03; board[0][4]=jLabel04; board[0][5]=jLabel05;
        board[1][0]=jLabel10; board[1][1]=jLabel11;board[1][2]=jLabel12;board[1][3]=jLabel13; board[1][4]=jLabel14; board[1][5]=jLabel15;
        board[2][0]=jLabel20; board[2][1]=jLabel21;board[2][2]=jLabel22;board[2][3]=jLabel23;board[2][4]=jLabel24;board[2][5]=jLabel25;
        board[3][0]=jLabel30; board[3][1]=jLabel31; board[3][2]=jLabel32;board[3][3]=jLabel33;board[3][4]=jLabel34;board[3][5]=jLabel35;
        board[4][0]=jLabel40; board[4][1]=jLabel41; board[4][2]=jLabel42; board[4][3]=jLabel43; board[4][4]=jLabel44; board[4][5]=jLabel45;
        board[5][0]=jLabel50;board[5][1]=jLabel51; board[5][2]=jLabel52;board[5][3]=jLabel53; board[5][4]=jLabel54; board[5][5]=jLabel55;
        
    }
   
  public void updateStatus(){
      if (logic.gameOver())
          {
              jMenuItemUndo.setEnabled(false);
            if (logic.gameStatus()==1)
            {
                jLabelCurrentStatus.setText("RED HAS WON!");
                redWin++;
                jLabelRedWin.setText("RED Winning:"+redWin);
            }
            else if (logic.gameStatus()==2)
            {
                jLabelCurrentStatus.setText("BLUE HAS WON!");
                blueWin++;
                jLabelBlueWin.setText("BLUE Winning:"+blueWin);
            }
            else
                jLabelCurrentStatus.setText("GAME ENDED TIED!");
            jButtonCol0.setEnabled(false);
            jButtonCol1.setEnabled(false);
            jButtonCol2.setEnabled(false);
            jButtonCol3.setEnabled(false);
            jButtonCol4.setEnabled(false);
            jButtonCol5.setEnabled(false);
            jMenuItemUndo.setEnabled(false);
          }
      else 
      {
          if (logic.undoable()==false)
              jMenuItemUndo.setEnabled(false);
          else
              jMenuItemUndo.setEnabled(true);
          if (logic.turn()==1)
            jLabelCurrentStatus.setText("Waiting for RED Player...");
          else
            jLabelCurrentStatus.setText("Waiting for BLUE Player...");
          jButtonCol0.setEnabled(true);
            jButtonCol1.setEnabled(true);
            jButtonCol2.setEnabled(true);
            jButtonCol3.setEnabled(true);
            jButtonCol4.setEnabled(true);
            jButtonCol5.setEnabled(true);
      }
  }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelCol0 = new javax.swing.JPanel();
        jLabel00 = new javax.swing.JLabel();
        jLabel01 = new javax.swing.JLabel();
        jLabel02 = new javax.swing.JLabel();
        jLabel03 = new javax.swing.JLabel();
        jLabel04 = new javax.swing.JLabel();
        jLabel05 = new javax.swing.JLabel();
        jPanelCol1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanelCol2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanelCol3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanelCol4 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanelCol5 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jPanelStatus = new javax.swing.JPanel();
        jLabelCurrentStatus = new javax.swing.JLabel();
        jLabelRedWin = new javax.swing.JLabel();
        jLabelBlueWin = new javax.swing.JLabel();
        jButtonCol0 = new javax.swing.JButton();
        jButtonCol1 = new javax.swing.JButton();
        jButtonCol2 = new javax.swing.JButton();
        jButtonCol3 = new javax.swing.JButton();
        jButtonCol4 = new javax.swing.JButton();
        jButtonCol5 = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuItemUndo = new javax.swing.JMenuItem();
        jMenuItemNewGame = new javax.swing.JMenuItem();
        jMenuItemLoadFile = new javax.swing.JMenuItem();
        jMenuItemSaveGame = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(50, 50));
        setMinimumSize(new java.awt.Dimension(50, 50));
        setPreferredSize(new java.awt.Dimension(850, 600));
        getContentPane().setLayout(null);

        jPanelCol0.setLayout(new java.awt.GridLayout(6, 1));

        jLabel00.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol0.add(jLabel00);

        jLabel01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol0.add(jLabel01);

        jLabel02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol0.add(jLabel02);

        jLabel03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol0.add(jLabel03);

        jLabel04.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol0.add(jLabel04);

        jLabel05.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol0.add(jLabel05);

        getContentPane().add(jPanelCol0);
        jPanelCol0.setBounds(24, 100, 133, 410);

        jPanelCol1.setLayout(new java.awt.GridLayout(6, 1));

        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol1.add(jLabel10);

        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol1.add(jLabel11);

        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol1.add(jLabel12);

        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol1.add(jLabel13);

        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol1.add(jLabel14);

        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol1.add(jLabel15);

        getContentPane().add(jPanelCol1);
        jPanelCol1.setBounds(157, 100, 130, 410);

        jPanelCol2.setLayout(new java.awt.GridLayout(6, 1));

        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol2.add(jLabel20);

        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol2.add(jLabel21);

        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol2.add(jLabel22);

        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol2.add(jLabel23);

        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol2.add(jLabel24);

        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol2.add(jLabel25);

        getContentPane().add(jPanelCol2);
        jPanelCol2.setBounds(287, 100, 130, 410);

        jPanelCol3.setLayout(new java.awt.GridLayout(6, 1));

        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol3.add(jLabel30);

        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol3.add(jLabel31);

        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol3.add(jLabel32);

        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol3.add(jLabel33);

        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol3.add(jLabel34);

        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol3.add(jLabel35);

        getContentPane().add(jPanelCol3);
        jPanelCol3.setBounds(417, 100, 130, 410);

        jPanelCol4.setLayout(new java.awt.GridLayout(6, 1));

        jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol4.add(jLabel40);

        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol4.add(jLabel41);

        jLabel42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol4.add(jLabel42);

        jLabel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol4.add(jLabel43);

        jLabel44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol4.add(jLabel44);

        jLabel45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol4.add(jLabel45);

        getContentPane().add(jPanelCol4);
        jPanelCol4.setBounds(547, 100, 130, 410);

        jPanelCol5.setLayout(new java.awt.GridLayout(6, 1));

        jLabel50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol5.add(jLabel50);

        jLabel51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol5.add(jLabel51);

        jLabel52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol5.add(jLabel52);

        jLabel53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol5.add(jLabel53);

        jLabel54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol5.add(jLabel54);

        jLabel55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCol5.add(jLabel55);

        getContentPane().add(jPanelCol5);
        jPanelCol5.setBounds(677, 100, 130, 410);

        jPanelStatus.setLayout(null);

        jLabelCurrentStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCurrentStatus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelStatus.add(jLabelCurrentStatus);
        jLabelCurrentStatus.setBounds(1, 9, 220, 30);

        jLabelRedWin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanelStatus.add(jLabelRedWin);
        jLabelRedWin.setBounds(430, 0, 120, 40);

        jLabelBlueWin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelBlueWin.setToolTipText("");
        jPanelStatus.add(jLabelBlueWin);
        jLabelBlueWin.setBounds(630, 0, 140, 40);

        getContentPane().add(jPanelStatus);
        jPanelStatus.setBounds(30, 0, 770, 40);

        jButtonCol0.setText("Column 0");
        buttonGroup1.add(jButtonCol0);
        jButtonCol0.setPreferredSize(new java.awt.Dimension(40, 23));
        jButtonCol0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCol0ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCol0);
        jButtonCol0.setBounds(30, 50, 120, 40);

        jButtonCol1.setText("Column 1");
        buttonGroup1.add(jButtonCol1);
        jButtonCol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCol1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCol1);
        jButtonCol1.setBounds(160, 50, 120, 40);

        jButtonCol2.setText("Column 2");
        buttonGroup1.add(jButtonCol2);
        jButtonCol2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCol2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCol2);
        jButtonCol2.setBounds(291, 50, 120, 40);

        jButtonCol3.setText("Column 3");
        buttonGroup1.add(jButtonCol3);
        jButtonCol3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCol3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCol3);
        jButtonCol3.setBounds(423, 50, 120, 40);

        jButtonCol4.setText("Column 4");
        buttonGroup1.add(jButtonCol4);
        jButtonCol4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCol4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCol4);
        jButtonCol4.setBounds(553, 50, 120, 40);

        jButtonCol5.setText("Column 5");
        buttonGroup1.add(jButtonCol5);
        jButtonCol5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCol5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCol5);
        jButtonCol5.setBounds(683, 50, 120, 40);

        jMenu.setBackground(java.awt.Color.blue);
        jMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu.setText("Menu");
        jMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItemUndo.setText("Undo");
        jMenuItemUndo.setToolTipText("");
        jMenuItemUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUndoActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemUndo);

        jMenuItemNewGame.setText("New Game");
        jMenuItemNewGame.setToolTipText("");
        jMenuItemNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewGameActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemNewGame);

        jMenuItemLoadFile.setText("Load File");
        jMenuItemLoadFile.setToolTipText("");
        jMenuItemLoadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoadFileActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemLoadFile);

        jMenuItemSaveGame.setText("Save Game");
        jMenuItemSaveGame.setToolTipText("");
        jMenuItemSaveGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveGameActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemSaveGame);

        jMenuBar.add(jMenu);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUndoActionPerformed
        
    if (lastEvent[0]=="jMenuItemUndo")
        jMenuItemUndo.setEnabled(false);
    else
    {
        int[]move= logic.lastMove();
        int row=move[1];
        int col=move[0];
       
        if (logic.turn()==1) 
            lastPlayer=Color.blue;
        else
            lastPlayer=Color.red;
        
            
        board[col][row].setBackground(new Color(0,0,0,0));
        board[col][row].setOpaque(false);
        
        logic.undoMove();
        jMenuItemUndo.setEnabled(false);
        updateStatus();   
        lastEvent[0]="jMenuItemUndo";
    }
    }//GEN-LAST:event_jMenuItemUndoActionPerformed

    private void jMenuItemLoadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoadFileActionPerformed
        
        
        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().createFileObject(System.getProperty("user.dir")));
        int r = j.showOpenDialog(null); 
        if (r == JFileChooser.APPROVE_OPTION) 
        {
        logic.loadBoard(j.getSelectedFile().getAbsolutePath()); 
        String[] rows=logic.toString().split("\n");
        for (int row=0;row<xsize;row++)
            for (int col=0;col<ysize;col++)
            {
                jMenuItemNewGame.setSelected(true);
                if (Character.getNumericValue((rows[row].charAt(col)))==1)
                {
                    board[col][row].setBackground(Color.red);
                    board[col][row].setOpaque(true);
                }
                else if (Character.getNumericValue((rows[row].charAt(col)))==2)
                {
                    board[col][row].setBackground(Color.blue);
                    board[col][row].setOpaque(true);
                }
                else
                {
                    board[col][row].setBackground(new Color(0,0,0,0));
                    board[col][row].setOpaque(false);
                }
            }
        updateStatus();
        jMenuItemUndo.setEnabled(false);
        lastEvent[0]="jMenuItemLoadFile";
        }
        
        
        
    }//GEN-LAST:event_jMenuItemLoadFileActionPerformed

    private void jMenuItemSaveGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveGameActionPerformed
       
        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().createFileObject(System.getProperty("user.dir")));
        //j.setApproveButtonText("Save");
        int r = j.showSaveDialog(null); 
        if (r == JFileChooser.APPROVE_OPTION) 
        {
            logic.saveBoard(j.getSelectedFile().getName()+".txt");
            lastEvent[0]="jMenuItemSaveGame";
        }
        
    }//GEN-LAST:event_jMenuItemSaveGameActionPerformed

    private void jMenuItemNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewGameActionPerformed
       
        this.setVisible(false);
        gui newGui=new gui();
        newGui.setVisible(true);
        lastEvent[0]="jMenuItemNewGame";
    }//GEN-LAST:event_jMenuItemNewGameActionPerformed

    private void jButtonCol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCol1ActionPerformed
if (logic.makeMove(1))
         {  
            if (logic.turn()==1) 
                lastPlayer=Color.blue;
            else
                lastPlayer=Color.red;
            int[]move= logic.lastMove();
            int row=move[1];
       
            
            board[1][row].setBackground(lastPlayer);
            board[1][row].setOpaque(true);
            lastEvent[0]="jButtonCol1";
         }
        updateStatus();       }//GEN-LAST:event_jButtonCol1ActionPerformed

    private void jButtonCol2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCol2ActionPerformed
if (logic.makeMove(2))
         {  
            if (logic.turn()==1) 
                lastPlayer=Color.blue;
            else
                lastPlayer=Color.red;
           
            int[]move= logic.lastMove();
        int row=move[1];
      
            
            board[2][row].setBackground(lastPlayer);
            board[2][row].setOpaque(true);
             lastEvent[0]="jButtonCol2";
         }
        updateStatus();       }//GEN-LAST:event_jButtonCol2ActionPerformed

    private void jButtonCol3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCol3ActionPerformed
if (logic.makeMove(3))
         {  
            if (logic.turn()==1) 
                lastPlayer=Color.blue;
            else
                lastPlayer=Color.red;
           
            int[]move= logic.lastMove();
        int row=move[1];
       
            
            board[3][row].setBackground(lastPlayer);
            board[3][row].setOpaque(true);
             lastEvent[0]="jButtonCol3";
         }
           

        updateStatus();         }//GEN-LAST:event_jButtonCol3ActionPerformed

    private void jButtonCol4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCol4ActionPerformed
 if (logic.makeMove(4))
         {  
            if (logic.turn()==1) 
                lastPlayer=Color.blue;
            else
                lastPlayer=Color.red;
           
            int[]move= logic.lastMove();
        int row=move[1];
            
            
            board[4][row].setBackground(lastPlayer);
            board[4][row].setOpaque(true);
             lastEvent[0]="jButtonCol4";
         }
                    
        updateStatus();     
             }//GEN-LAST:event_jButtonCol4ActionPerformed

    private void jButtonCol5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCol5ActionPerformed
 if (logic.makeMove(5))
         {  
            if (logic.turn()==1) 
                lastPlayer=Color.blue;
            else
                lastPlayer=Color.red;
           
            int[]move= logic.lastMove();
        int row=move[1];
    
            board[5][row].setBackground(lastPlayer);
            board[5][row].setOpaque(true);
             lastEvent[0]="jButtonCol5";
         }
        updateStatus();                }//GEN-LAST:event_jButtonCol5ActionPerformed

    private void jButtonCol0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCol0ActionPerformed
if (logic.makeMove(0))
         {  
            if (logic.turn()==1) 
                lastPlayer=Color.blue;
            else
                lastPlayer=Color.red;
           
            int[]move= logic.lastMove();
        int row=move[1];
               
            board[0][row].setBackground(lastPlayer);
            board[0][row].setOpaque(true);
             lastEvent[0]="jButtonCol0";
         }

        updateStatus();     
             }//GEN-LAST:event_jButtonCol0ActionPerformed

    
     // @param args the command line arguments
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCol0;
    private javax.swing.JButton jButtonCol1;
    private javax.swing.JButton jButtonCol2;
    private javax.swing.JButton jButtonCol3;
    private javax.swing.JButton jButtonCol4;
    private javax.swing.JButton jButtonCol5;
    private javax.swing.JLabel jLabel00;
    private javax.swing.JLabel jLabel01;
    private javax.swing.JLabel jLabel02;
    private javax.swing.JLabel jLabel03;
    private javax.swing.JLabel jLabel04;
    private javax.swing.JLabel jLabel05;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabelBlueWin;
    private javax.swing.JLabel jLabelCurrentStatus;
    private javax.swing.JLabel jLabelRedWin;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemLoadFile;
    private javax.swing.JMenuItem jMenuItemNewGame;
    private javax.swing.JMenuItem jMenuItemSaveGame;
    private javax.swing.JMenuItem jMenuItemUndo;
    private javax.swing.JPanel jPanelCol0;
    private javax.swing.JPanel jPanelCol1;
    private javax.swing.JPanel jPanelCol2;
    private javax.swing.JPanel jPanelCol3;
    private javax.swing.JPanel jPanelCol4;
    private javax.swing.JPanel jPanelCol5;
    private javax.swing.JPanel jPanelStatus;
    // End of variables declaration//GEN-END:variables
}
